### ISSUE TITLE
FlexBox expanding style

### ISSUE THREAD

**Issue by DustinLin** [DustinLin/datavisTrainsPlanes#1]
The `<Map/>` and `<RouteDisplay/>` currently have hardcoded dimensions. Not really ideal but also not high priority.

Currently using a flexbox container to align the items, but the problem is `<RouteDisplay/>` width would grow based on what text is being rendered. This is a problem because it causes the flexbox to "push" the map around, which messes with the onHover event nature.

The current fix is to just make the `<RouteDisplay/>` wide enough to render any possible text inside, but maybe a ideal situation is for the component to fill up the remaining horizontal space, so it has room to render the text without pushing the map around.

Before: 
![Screen Shot 2024-04-06 at 11 23 17 AM](https://github.com/DustinLin/datavisTrainsPlanes/assets/39450497/bf339080-a400-4fe2-81fe-dfd33d417113)

![Screen Shot 2024-04-06 at 11 24 03 AM](https://github.com/DustinLin/datavisTrainsPlanes/assets/39450497/548f43d7-b893-4209-8d40-59854a3861d5)

The above is a problem as mentioned, ideally want the element's width to be larger, and not be bounded by the text

![Screen Shot 2024-04-06 at 11 24 51 AM](https://github.com/DustinLin/datavisTrainsPlanes/assets/39450497/27520b77-0ac2-4f8a-b9f2-87c41bc61d68)

When hovering over a line, can see the map shifting over to the left, which makes the path that was just being hovered go out of range (the blue box).

**Comment by JJEW22** [comment]
Got it to be flexible.
